server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:starWars
    username: sa
    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl